services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    networks:
      - currency-converter-network
    env_file:
      - ./env/.env.development

  redis:
    image: redis:8.2.1-alpine3.22
    ports:
      - "7389:6379"
    networks:
      - currency-converter-network

  test-runner:
    build:
      context: .
      dockerfile: tests/Dockerfile.tests
    volumes:
      - ./CodeCoverage:/CodeCoverage
    networks:
      - currency-converter-network
    environment:
      - OTEL_DOTNET_AUTO_ENABLED=false

  nginx:
    image: nginx:1.29.1-alpine3.22
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapi
      - test-runner
    networks:
      - currency-converter-network

networks:
  currency-converter-network:
    driver: bridge